### PR TITLE
bug fix: Routes change and navigation

### LINKED ISSUE #91: Bug fix and Whole Routing
index.html , index.js
routing structure (consider base_url = "...../index.html" or "www.domain.com"
```

1. when url is hit 
base_url
	?q=analyze --> show input container
	otherwise  --> show landing container
			
2. Our routing Structure (no refresh should take place,route should be changed, you may use function like window.history.pushstate())

	analyze btn clicked ->  ?q=analyze
	form submitted      ->  ?q=result 

current bugs 
	1. When base_url?q=analyze is refreshed, a glimpse of landing is seen (you may hide all 3 divs initially and show according to route)
	2. click analyze btn, ?q=analyze will open, but on pressing back(browser's back) only url changes (on back, you may reload the page after changing url)
```
You have to do the routing and fix the bugs.
**Before commenting make sure you have a well executable plan, and you have explored how to do each step clearly**
**Participants with excellent js skill should ask for this assignment**
In case of doubts asked.

### PR DESCRIPTION
**Pull request by abhushanaj**
closes #91 
Does the following
- correctly re renders the divs on routes change
- movement to go back and re render
- CSS big fix on unwanted display
- gives landing page as a fallback on unwanted routes

@rajats98  Sir, let me know if it's okay! Thanks!

### CODE REVIEW

File: src/assets/index.js [hunk 1]
```diff
@@ -105,29 +93,73 @@ const update_result = (report) => {
...
 
 
+
+
+
+const form = document.querySelector(".upload-form");
+form.addEventListener("submit", (e) => {
+    event.preventDefault();
+    window.location.assign('/src/index.html?q=result');
+    show_result_container();
```
Comment (rajats98) [inline src/assets/index.js]: change '/src/index.html?q=result' to '?q=result, everywhere
remove show_result_container() from line 108

File: src/assets/index.js [hunk 2]
```diff
@@ -105,29 +93,73 @@ const update_result = (report) => {
...
+/* 
+  ---------------------------
+    All Code for routing 
+  -----------------------------  
+ 
+  */
+
+const analyze_click = () => {
+    window.location.assign('/src/index.html?q=analyze');
+    show_input_container();
```
Comment (rajats98) [inline src/assets/index.js]: remove show_input_container function from here, it is redundant

File: src/assets/index.js [hunk 3]
```diff
@@ -118,16 +118,39 @@ const showImage = event => {
...
+    
+window.addEventListener('popstate', () => {
+    
+    console.log(SectionToBeDisplay);
+    window.location.reload();
+    if (SectionToBeDisplay === 'analyze') {
+        window.history.pushState("Landing Page", "Crop AI", 'index.html');
+        show_landing_container();
+    }
+
```
Comment (rajats98) [inline src/assets/index.js]: I think this **if condition** is not required
I don't think it is ever executed, as the page refreshed before that
